config/routes.rb
require File.expand_path("../../lib/logged_in_constraint", __FILE__)

Fastspec::Application.routes.draw do
  #ActiveAdmin.routes(self)


  authenticated :user do
    root :to => 'dashboard#index'
  end

  root :to => "home#index"
  match 'dashboard' => "dashboard#index", as: 'dashboard'
  match 'home' => "home#index", as: 'home'

  
  devise_for :users
  resources :users, :only => [:show, :index]
  match 'user/rolify' => 'users#rolify'

  #devise_for :users, ActiveAdmin::Devise.config
  
  resources :projects
  resources :teams
  resources :features

  match 'projects/:id/add/feature/:feature_id' => 'projects#add_feature', as: 'project_add_feature'
  match 'projects/:id/delete/feature/:feature_id' => 'projects#delete_feature', as: 'project_delete_feature'
  match 'projects/:id/update/feature/:feature_id' => 'projects#update_feature', as: 'project_update_feature'
  match 'projects/:id/update/features' => 'projects#update_features', as: 'project_update_features'

  match 'projects/:id/share' => 'projects#share', as: 'share_project'
  match 'projects/:id/unshare' => 'projects#unshare', as: 'unshare_project'
  match 'p/:token' => 'projects#shared', as: 'shared_project'
  
  resources :invites
  match 'invite' => 'invites#new', as: 'new_invite'
  match 'reinvite/:token' => 'invites#reinvite', as: 'resend_invite'
  match 'join/:token' => 'invites#join', as: 'join_invite'

  match 'changelog' => 'changelog#index'

  namespace "api" do
    namespace "v1" do
      get "features" => "features#get"
      post 'project/feature' => 'features#add_feature_to_project'
      post 'project/feature/comment' => 'features#add_comment_to_feature'
      delete 'project/feature' => 'features#remove_feature_from_project'
      post 'project/feature/attach' => 'features#attach_picture_to_feature'
    end
    
  end

end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Roles::Object
  
  field :name, :type => String
  field :share_token, :type => String

  belongs_to :team

  embeds_many :project_features, :inverse_of => :project, cascade_callbacks: true
  #accepts_nested_attributes_for :project_features

  include TeamHelper
  #scope :in_team, { where(team_id: TeamHelper.current_team_id) }
  scope :in_team, ->(t) { where(team_id: t.id) }
  #default_scope where(team_id: TeamHelper.current_team_id)
  

  def self.find_by_share_token(token)
    self.find_by(share_token: token)
  end

  def total_estimate
    self.project_features.sum(:estimate)
  end
  

end

app/controllers/projects_controller.rb
  class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:shared]
  respond_to :html, :json, :pdf
  layout "preview", :only => [:shared]
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.in_team(current_team).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    #puts "--> #{Project.in_team.inspect}"
    @project = Project.in_team(current_team).find(params[:id])
    @features = @project.project_features.asc(:index)
    
    out_project = @project
    out_project.project_features.asc(:index).each_with_index { |pf, index|
      out_project.project_features[index][:project_id] = @project.id.to_s
    }
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: out_project }
      format.pdf
    end
  end

  def share
    @project = Project.in_team(current_team).find(params[:id])
    @project.share_token ||= Devise.friendly_token[0,7]
    @project.save

    render :show
  end

  def unshare
    @project = Project.in_team(current_team).find(params[:id])
    @project.share_token = nil
    @project.save

    render :show
  end

  def shared
    @project = Project.find_by_share_token(params[:token])
    @features = @project.project_features.asc(:index)
    @team = (@project.team rescue nil)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
      format.pdf
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.in_team(current_team).find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.team = current_team

    current_user.has_role!(:write, @project)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.in_team(current_team).find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { respond_with_bip @project }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.in_team(current_team).find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end


  def add_feature
    @project = Project.in_team(current_team).find(params[:id])

    feature = (Feature.find(params[:feature_id]) rescue nil)

    if feature.nil?
      redirect_to @project, alert: 'Feature was not found.' and return
    end

    feature_image = feature.image

    #@project.project_features = nil

    project_feature = ProjectFeature.new_from_feature(feature)
    project_feature.index = @project.project_features.count

    if @project.project_features << project_feature

      project_feature.image.store! feature_image.file if feature_image
      project_feature.save!

      @project.save

      redirect_to @project, notice: 'Feature was was added.'
    else
      redirect_to @project, alert: 'Problem adding Feature.'
    end
  end

  def delete_feature
    @project = Project.in_team(current_team).find(params[:id])
    feature = (@project.project_features.find(params[:feature_id]) rescue nil)

    if feature.nil?
      redirect_to @project, alert: 'Feature was not found.' and return
    end
      
    # TODO: Delete image also
    
    if @project.project_features.where(:_id => feature.id.to_s).delete_all
      #@project.reload
      redirect_to @project, notice: 'Feature was deleted.'
    else
      redirect_to @project, alert: 'Problem removing Feature.'
    end
    
  end

  def update_feature
    @project = Project.in_team(current_team).find(params[:id])
    feature = (@project.project_features.find(params[:feature_id]) rescue nil)

    if feature
      feature.attributes = params[:project_feature]
      if @project.save
        respond_with_bip feature
      else 
        logger.error "Cannot save project"  
      end    
    end
  end

  def update_features
    @project = Project.in_team(current_team).find(params[:id])

    index = 0
    @project.project_features.asc(:index).each do |f|
      original_feature = (Feature.find(f.original_id) rescue nil)
      if original_feature
        feature_image = original_feature.image
        attributes = f.attributes_from_feature(original_feature)
        #puts "---> attributes: #{attributes.inspect}"
        f.attributes = attributes
        f.index = index

        f.image.store! feature_image.file if feature_image
        f.save!

        @project.save
        index += 1
      end
    end

    redirect_to @project, alert: 'Features were updated!' and return
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for @project, html: { class: 'form-horizontal' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit
    - if @project.persisted?
      = link_to 'Destroy', @project, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-danger'
    

app/views/projects/_project_feature.html.haml
%tr{:"data-toggle"=> "collapse", :"data-target"=>"#details_#{f.id}", :"data-row-feature-id" => f.id}
  %td
    %img{:id => "img#{f.id}", :src => f.image.small_thumb}
    = best_in_place f, :name, path: project_update_feature_path(@project, f), nil: 'Something'
  %td= best_in_place f, :estimate, path: project_update_feature_path(@project, f), nil: 0
  %td{:style => 'text-align: right'}
    - if f.comments.count > 0
      %i.icon-comment{:style => 'opacity:0.8'}
      = f.comments.count
    %button.btn.btn-mini.btn-danger.remove_feature_btn{:'data-feature-id' => f.id}
      Remove

%tr{:"data-row-feature-id" => f.id}
  %td{:colspan => 3, :style => 'height: 0px; padding:0; margin: 0; border-top: 0;'}
    %div.collapse{:id => "details_#{f.id}"}   
      .alert.alert-info
        .row-fluid
          .span10
            = best_in_place f, :description, path: project_update_feature_path(@project, f), nil: "Enter Description of this Task"    
          .span2
            -#= image_tag(f.image.thumb, :id => "img_100_#{f.id}") 
            %a.lightbox{:href => f.image.url, :title => f.name}
              %img{:id => "img_100_#{f.id}", :src => f.image.thumb}

      %br
      .comments{:id => "comments_#{f.id}"}
        - f.comments.each do |com|
          .alert.alert-info
            = com.comment
            %br
            %br
            %span.label #{com.user_name}, #{time_ago_in_words(com.created_at)}

      .btn-group{:style => 'margin:5px;'}
        %button.add_comment_btn.btn.btn-success.btn-mini{:'data-feature-id' => f.id}
          Add comment
        %button.add_image_btn.btn.btn-alert.btn-mini{:'data-feature-id' => f.id}
          Attach image

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1.page-header My Projects

.btn-toolbar
  %button.btn.btn-primary#add_project_btn
    Add project
    
      
%table.table.table-striped
  %tr
  
  - @projects.each do |project|
    %tr
      %td
        = link_to project.name, project
      %td
        .btn-group
          = link_to 'Edit', edit_project_path(project), {:class => 'btn btn-primary btn-mini'}
          = link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-mini'
          -#%button{:"data-toggle"=> "collapse", :"data-target"=>"details_#{project.id}", :class => 'btn btn-primary btn-mini'}
    -#%tr
    -#  %div.collapse{:id => "details_#{project.id}"}    
    -#    Test ingo
%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

app/views/projects/shared.html.haml
-#- content_for :logo do
-#  = image_tag @team.image if @team.image?

.row-fluid
  .span8
    %h1.page-header= @project.name
  .span4
    = image_tag @team.image, height: '100' if @team.image?

%table.table.table-striped
  %thead
    %tr
      %th{style:'width: 30px'} #
      %th{style:'width: 25px'}
      %th Feature
      %th Estimate, hours

  %tbody
    - total = 0
    - @features.each do |f|
      - total += f.estimate
      %tr
        %td= (f.index + 1 rescue '')
        %td
          - if f.image?
            %a.lightbox{:href => "#{f.image.url}", :title => "#{f.name}"}
              = image_tag(f.image.small_thumb)
        %td= f.name
        %td= f.estimate
  %tfoot
    %tr
      %td
      %td
      %td Total, hours:
      %td= total
          
= link_to(shared_project_path(@project.share_token, :format => :pdf), :target => "_blank", class: 'btn js-btn') do
  %i.icon-print
  Print PDF »
  
/
  %a.print-preview
    %i.icon-print
    Print »

app/views/projects/show.html.haml
%h1.page-header 
  = best_in_place @project, :name

.btn-toolbar
  %button.btn.btn-primary#add_feature_btn{:"data-toggle" => "modal"}
    Add feature

%table.table.table-striped.table-condensed{:id => 'featureListTable'}
  %tr
    %th{style:'width: 30px'} #
    %th{style:'width: 25px'}
    %th Feature
    %th Estimate, hours
    %th

  -#%tr= render partial: 'project_feature', collection: @project.project_features, as: :f    
  %tr= render :partial => 'shared/templates/project_feature', :handler => :haml, :collection => @features
  %tr
    %td
    %td
    %td
    %td Total, hours:
    %td
      %span.label.label-success#estimate_total
        x
          
/
  = link_to 'Edit', edit_project_path(@project)
  \|
  = link_to 'Back', projects_path


  
= link_to(project_path(@project, :format => :pdf), :target => "_blank", class: 'btn js-btn') do
  %i.icon-print
  Print PDF »
  
/
  %a.print-preview
    %i.icon-print
    Print »
/
  #share-container
    %span.shared
      %strong Shared:
      %a{href:'#'}
    = link_to(share_project_path(@project), class: 'share-link', remote: true) do
      %i.icon-share-alt
      Share
    = link_to(unshare_project_path(@project), class: 'unshare-link') do
      %i.icon-remove


- if @project.share_token
  %b Shared:
  - shared_url = shared_project_url(@project.share_token)
  = link_to(shared_url, shared_url)
  = icon_hint_link_to 'remove', 'Un-share Project', unshare_project_path(@project)
- else
  = icon_link_to 'share-alt', 'Share', share_project_path(@project)

%br
%br

.btn-group
  %button.btn.dropdown-toggle{'data-toggle' => 'dropdown'}
    Actions
    %span.caret
  %ul.dropdown-menu
    %li
      = link_to 'Update features from masters', project_update_features_path(@project), :confirm => 'Are you sure? This will remove all your changes!'


#add_comment_form.modal.hide.fade{:'data-project-id' => @project.id}
  .modal-header
    %button.close{:"data-dismiss" =>"modal"}
      x
    %h3 Comment
  .modal-body#comment_form.form-horizontal
    .control-group
      %label.control-label{:for => 'comment_fld'}
        Enter your comment
      .controls
        %input.input-xlarge#comment_fld{:type => 'text'}
    
  .modal-footer
    %button.btn{:"data-dismiss" =>"modal"}
      Close
    %button.btn.btn-success#save_comment_btn{:'data-project-id' => @project.id}
      Save  

#add_feature_popup.modal.hide.fade{:'data-project-id' => @project.id}
  .modal-header
    %button.close{:"data-dismiss" =>"modal"}
      x
    %h3 Add a Feature
  .modal-body#features_list
  .modal-footer
    %button.btn{:"data-dismiss" =>"modal"}
      Close

#add_image_popup.modal.hide.fade{:'data-project-id' => @project.id}
  .modal-header
    %button.close{:"data-dismiss" =>"modal"}
      x
    %h3 Attach Image
  .modal-body
    = form_tag(api_v1_project_feature_attach_path(:format => :js), {:remote => true, :id => "attach_image_form"}) do
      = file_field_tag(:image)
      = submit_tag "Attach"
      = hidden_field_tag :pid
      = hidden_field_tag :fid
      
      
  .modal-footer
    %button.btn{:"data-dismiss" =>"modal"}
      Close
    -#
    %button.btn.btn-success#attach_image_btn{:'data-project-id' => @project.id}
      Attach  
      
%script{:type => 'text/javascript'}
  $(document).ready(function() {
  $(document.body).trigger('FS::FeatureListUpdated');
  });
  