config/routes.rb
require File.expand_path("../../lib/logged_in_constraint", __FILE__)

Fastspec::Application.routes.draw do
  #ActiveAdmin.routes(self)


  authenticated :user do
    root :to => 'dashboard#index'
  end

  root :to => "home#index"
  match 'dashboard' => "dashboard#index", as: 'dashboard'
  match 'home' => "home#index", as: 'home'

  
  devise_for :users
  resources :users, :only => [:show, :index]
  match 'user/rolify' => 'users#rolify'

  #devise_for :users, ActiveAdmin::Devise.config
  
  resources :projects
  resources :teams
  resources :features

  match 'projects/:id/add/feature/:feature_id' => 'projects#add_feature', as: 'project_add_feature'
  match 'projects/:id/delete/feature/:feature_id' => 'projects#delete_feature', as: 'project_delete_feature'
  match 'projects/:id/update/feature/:feature_id' => 'projects#update_feature', as: 'project_update_feature'
  match 'projects/:id/update/features' => 'projects#update_features', as: 'project_update_features'

  match 'projects/:id/share' => 'projects#share', as: 'share_project'
  match 'projects/:id/unshare' => 'projects#unshare', as: 'unshare_project'
  match 'p/:token' => 'projects#shared', as: 'shared_project'
  
  resources :invites
  match 'invite' => 'invites#new', as: 'new_invite'
  match 'reinvite/:token' => 'invites#reinvite', as: 'resend_invite'
  match 'join/:token' => 'invites#join', as: 'join_invite'

  match 'changelog' => 'changelog#index'

  namespace "api" do
    namespace "v1" do
      get "features" => "features#get"
      post 'project/feature' => 'features#add_feature_to_project'
      post 'project/feature/comment' => 'features#add_comment_to_feature'
      delete 'project/feature' => 'features#remove_feature_from_project'
      post 'project/feature/attach' => 'features#attach_picture_to_feature'
    end
    
  end

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{href: "#", "data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to_unless_current("Fastspec", root_path, :class => 'brand') do
  = link_to("Fastspec", home_path, :class => 'brand')

- if user_signed_in?
  - if current_team
    %ul.nav
      %li.dropdown
        %a.dropdown-toggle{ 'href'=> '#', 'data-toggle' => 'dropdown' }
          = current_team.name
          %b.caret
        %ul.dropdown-menu
          - current_user.teams.each do |team|
            %li= link_to team.name, team
          %li.divider
          %li= link_to 'Edit current team', edit_team_path(current_team)
          %li= link_to 'Create new team', new_team_path
      %li= link_to 'Invite friends', new_invite_path

%ul.nav.pull-right
  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle{ 'href'=> '#', 'data-toggle' => 'dropdown' }
        = gravatar_image_tag(current_user.email, gravatar: {size: 20})
        = current_user.name
        %b.caret
      %ul.dropdown-menu
        %li= link_to 'Edit account', edit_user_registration_path
        %li= link_to('Logout', destroy_user_session_path, :method=>'delete')
  - else
    %li= link_to('Login', new_user_session_path)
    %li= link_to('Sign up', new_user_registration_path)
  %li.divider-vertical
  %li= link_to 'Changelog', changelog_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Fastspec"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = analytics_init :local => Rails.env.development?
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield
        /
          .content
            .row
              .span12
        %footer.footer
          %p 
            Build with love by 
            %a{href: 'http://appfellas.co', target: '_blank'} AppFellas

app/views/layouts/preview.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Fastspec"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = analytics_init :local => Rails.env.development?
    = csrf_meta_tags
    = yield(:head)
  %body.preview
    #main{:role => "main"}
      .container
        = yield(:logo)
        = yield
        /
          .content
            .row
              .span12
        %footer.footer
          %p
            %em Made by 
            %a.brand{href: 'http://fastspec.me', target: '_blank'} FastSpec